# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SabadBan' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Localize-Swift', '~> 1.5'
  pod 'Alamofire-Gloss'
  pod 'SwiftEventBus'
  pod 'BTNavigationDropdownMenu'
  pod 'ActionButton'
  pod 'SQLite.swift'
end
