# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def sabadBanPods

  pod 'Localize-Swift', '~> 1.5'
  pod 'Alamofire-Gloss’
  pod 'Alamofire’
  pod 'SwiftEventBus'
  pod 'BTNavigationDropdownMenu'
  pod 'SQLite.swift'
  pod 'FCAlertView'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :branch => 'swift2.0'
  pod 'GSMessages','~> 1.2.3'
  
end


target 'SabadBanDev' do
sabadBanPods
end

target 'SabadBanTest' do
sabadBanPods
end

target 'SabadBanProd' do
sabadBanPods
end
